spring.application.name=orbit-backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS configuration
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}
cors.allowed.methods=${CORS_ALLOWED_METHODS}

# JWT
jwt.secret.key=${JWT_SECRET:}
jwt.access-token-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:3600000}
jwt.refresh-token-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Actuator
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=when_authorized

# Esewa Payment Gateway
esewa.product-code=${ESEWA_PRODUCT_CODE:}
esewa.secret-key=${ESEWA_SECRET_KEY:}

esewa.success-callback-url=${ESEWA_SUCCESS_CALLBACK_URL:}
esewa.failure-callback-url=${ESEWA_FAILURE_CALLBACK_URL:}

esewa.frontend-success-url=${ESEWA_FRONTEND_SUCCESS_URL:}
esewa.frontend-failure-url=${ESEWA_FRONTEND_FAILURE_URL:}

esewa.status-url=${ESEWA_STATUS_URL:}